/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tester_Tracer */

#ifndef _Included_tester_Tracer
#define _Included_tester_Tracer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tester_Tracer
 * Method:    runGST
 * Signature: (JI)Ltester/Trace;
 */
JNIEXPORT jobject JNICALL Java_tester_Tracer_runGST
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     tester_Tracer
 * Method:    runASGCT
 * Signature: (JI)Ltester/Trace;
 */
JNIEXPORT jobject JNICALL Java_tester_Tracer_runASGCT
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     tester_Tracer
 * Method:    runASGST
 * Signature: (II)Ltester/Trace;
 */
JNIEXPORT jobject JNICALL Java_tester_Tracer_runASGST
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     tester_Tracer
 * Method:    runASGSTInSignalHandler
 * Signature: (IJI)Ltester/Trace;
 */
JNIEXPORT jobject JNICALL Java_tester_Tracer_runASGSTInSignalHandler
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     tester_Tracer
 * Method:    runASGSTInSeparateThread
 * Signature: (IJI)Ltester/Trace;
 */
JNIEXPORT jobject JNICALL Java_tester_Tracer_runASGSTInSeparateThread
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     tester_Tracer
 * Method:    getJavaThreadIds
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tester_Tracer_getJavaThreadIds
  (JNIEnv *, jclass);

/*
 * Class:     tester_Tracer
 * Method:    getOSThreadIds
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_tester_Tracer_getOSThreadIds
  (JNIEnv *, jclass);

/*
 * Class:     tester_Tracer
 * Method:    getOSThreadId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_tester_Tracer_getOSThreadId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     tester_Tracer
 * Method:    getCurrentOSThreadId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tester_Tracer_getCurrentOSThreadId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
